### ISSUE TITLE
undefined method `to_i' for #

### ISSUE THREAD

**Issue by bprodoehl** [prove/tarantula#48]
If I try to save a new Set, or try to save changes to an existing Execution, I get "undefined method `to_i' for #".  This is on a new install on CentOS 6.3 i386, following the instructions here: https://github.com/prove/tarantula/blob/master/README.md

I haven't hooked it up to a defect tracker, if that matters.  Also, I can do the same operations on the demo site and it works fine there.

Here is part of the backtrace:

undefined method `to_i' for #<Admin:0xb2e35a0>
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.11/lib/active_model/attribute_methods.rb:407:in`method_missing'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_methods.rb:149:in `method_missing'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/column.rb:178:in`value_to_integer'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/column.rb:78:in `type_cast'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_methods/dirty.rb:86:in`_field_changed?'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_methods/dirty.rb:63:in `write_attribute'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_methods/write.rb:14:in`updated_by='
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_assignment.rb:85:in `block in assign_attributes'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_assignment.rb:78:in`each'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/persistence.rb:227:in`block in update_attributes!'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in `transaction'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:311:in`with_transaction_returning_status'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/persistence.rb:226:in `update_attributes!'
/opt/tarantula/rails/app/models/core/execution.rb:212:in`block in update_with_assignments!'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:208:in`transaction'
/opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.11/lib/active_record/transactions.rb:250:in `transaction'
/opt/tarantula/rails/app/models/core/execution.rb:206:in`update_with_assignments!'
/opt/tarantula/rails/app/controllers/executions_controller.rb:114:in `update'

**Comment by bprodoehl** [comment]
This patch fixes the issue, but it almost certainly can't be used as-is the way I'm pasting it in here:

From 871d05c745ed2b40c038e21a1111923606683b72 Mon Sep 17 00:00:00 2001
From: Brian Prodoehl bprodoehl@connectify.me
Date: Thu, 17 Jan 2013 15:03:11 -0500
Subject: [PATCH] Fix set creation and execution updating under new Rails

---

 app/controllers/executions_controller.rb | 2 +-
 app/controllers/test_sets_controller.rb  | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/app/controllers/executions_controller.rb b/app/controllers/executions_controller.rb
index 6cccf79..ee4e196 100644
--- a/app/controllers/executions_controller.rb
+++ b/app/controllers/executions_controller.rb
@@ -106,7 +106,7 @@ class ExecutionsController < ApplicationController
       return
     end
     @data['version'] = params['version'] # TODO: ???????
-    @data['updated_by'] = @current_user
-    @data['updated_by'] = @current_user.id
  
   cases = @data.delete('cases')
   tag_list = @data.delete('tag_list')
  diff --git a/app/controllers/test_sets_controller.rb b/app/controllers/test_sets_controller.rb
  index eb55f9f..b709576 100644
  --- a/app/controllers/test_sets_controller.rb
  +++ b/app/controllers/test_sets_controller.rb
  @@ -32,7 +32,7 @@ class TestSetsController < ApplicationController
   tag_list = @data.delete(:tag_list)
   case_data = @data.delete(:cases)
   @data[:project_id] = @project.id
-    @data[:created_by] = @data[:updated_by] = @current_user
-    @data[:created_by] = @data[:updated_by] = @current_user.id
  
   @set = TestSet.create_with_cases!(@data, case_data, tag_list)

@@ -50,7 +50,7 @@ class TestSetsController < ApplicationController
     tag_list = @data.delete(:tag_list)
     case_data = @data.delete(:cases)
     @data[:project_id] = @project.id if @data[:project_id].nil?
-    @data[:updated_by] = @current_user
-    @data[:updated_by] = @current_user.id
  
   @test_set.update_with_cases!(@data, case_data, tag_list)

## 

1.7.11.7

**Comment by bprodoehl** [comment]
This is addressed in my pull request.
