### ISSUE TITLE
Applicaiton does not start after successful install

### ISSUE THREAD

**Issue by getrupendra** [prove/tarantula#75]
I successfully installed tarantula using Manual instructions. 

after Reboot 
ruby -v 
ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux]

rails -v 
Rails 3.2.18

But when I start applicaiton it gives following error in /var/log/httpd/error_log:

[ 2015-08-28 19:13:34.0212 2228/b772cb70 Pool2/Pool.h:777 ]: Process (pid=29975, group=/opt/tarantula/rails#default) no longer exists! Detaching it from the pool.
App 29984 stdout:
App 3557 stderr: /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:356:in `trap'
App 3557 stderr: :
App 3557 stderr: Invalid argument - SIGKILL
App 3557 stderr:  (
App 3557 stderr: Errno::EINVAL
App 3557 stderr: )
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:356:in`block in reset_signal_handlers'
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:354:in `each_key'
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:354:in`reset_signal_handlers'
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:182:in `main_loop'
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:161:in`module:App'
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
App 3557 stderr:        from /opt/tarantula/rails/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.45/helper-scripts/rack-preloader.rb:28:in`<main>'

Can someone suggest how to solve this?

Thanks in Advance.

**Comment by kirantpatil** [comment]
you may try https://github.com/msjit/testcasedb/
